#ifndef _INPUT_EVENT_H
#define _INPUT_EVENT_H

enum class EventId
{
    PRESS_UP,
    PRESS_DOWN,
    PRESS_LEFT,
    PRESS_RIGHT,
    UNPRESS_UP,
    UNPRESS_DOWN,
    UNPRESS_LEFT,
    UNPRESS_RIGHT,
    // NOTE: (TODO) CURRENTLY ONLY SUPPORTING INSTANTANEOUS ACTIONS
    PRESS_ACTION,
    // UNPRESS_ACTION,
    // PRESS_INTERACT,
    // UNPRESS_INTERACT,
    // PRESS_SPRINT,
    // UNPRESS_SPRINT
    ROTATE_INVENTORY
};

#endif