#ifndef _SPRITE_TYPE_H
#define _SPRITE_TYPE_H

enum class SpriteType
{
    PLAYER,
    // NOTE: CURRENT NPC-SPRITETYPES DETERMINE ONLY THEIR BEHAVIOR,
    // AND NO OTHER PROPERTIES (E.G., WHAT THEY LOOK LIKE)
    PATROLLER,
    FOLLOWER,
    WANDERER,
    IDLER
};

#endif